### ISSUE TITLE
CRASH: PasswordHash not loaded when needed

### ISSUE THREAD

**Issue by My1** [Ayesh/wordpress-password-hash#3]
~~~
[23-Oct-2017 08:28:42 UTC] PHP Fatal error:  Uncaught Error: Class 'PasswordHash' not found in /home/my1devcon/public_html/wptest/wp-content/plugins/password-hash-disabled/wp-php-password-hash.php:64
Stack trace:
#0 /home/my1devcon/public_html/wptest/wp-includes/user.php(162): wp_check_password('test', '$P$BzCPKMBr7KO3...', 1)
#1 /home/my1devcon/public_html/wptest/wp-includes/class-wp-hook.php(298): wp_authenticate_username_password(Object(WP_User), 'My1', 'test')
#2 /home/my1devcon/public_html/wptest/wp-includes/plugin.php(203): WP_Hook->apply_filters(NULL, Array)
#3 /home/my1devcon/public_html/wptest/wp-includes/pluggable.php(532): apply_filters('authenticate', NULL, 'My1', 'test')
#4 /home/my1devcon/public_html/wptest/wp-includes/user.php(85): wp_authenticate('My1', 'test')
#5 /home/my1devcon/public_html/wptest/wp-login.php(790): wp_signon(Array, true)
#6 {main}
  thrown in /home/my1devcon/public_html/wptest/wp-content/plugins/password-hash-disabled/wp-php-password-hash.php on line 64
~~~

I tried both on my main and test blog, both on 4.8.2 and got server fails, upon investigating I saw that phpass hasnt been loaded yet. #2 has a hotfix for this.

I tried checking for the class and requiring the file if the class isnt loaded. should be enough for a hotfix.

as this is an issue that renders the login unusable, this need to be thrown out quickly.

**Comment by yet-another-Daniel** [comment]
I have the same issue:

PHP Fatal error:  Uncaught Error: Class 'PasswordHash' not found in /www/htdocs/.../.../.../wp-content/plugins/password-hash/wp-php-password-hash.php:64

**Comment by My1** [comment]
just go to the pull request I made and do the change shown there, that solves it.

**Comment by yet-another-Daniel** [comment]
Thank you, My1.

**Comment by My1** [comment]
no problem, although I wonder what the dev is doing after all this was made more than a month ago and quite a trivial fix, shouldnt need much of a review.

**Comment by Ayesh** [comment]
Hi @yet-another-Daniel - Sorry about the delay on my end. I was quite overwhelmed with some work here. #2 helped, and we now have a 1.4 version on wordpress.org with the fix.

**Comment by My1** [comment]
okay, but kinda sad that you had so much work, the PR and everything was already set and tested by it's author. but also weird why WP changed something that in result broke this.

**Comment by Ayesh** [comment]
My new year resolution is to pay more attention to the PRs and issues :) I apologize for the delay on my part. 

As for the bug not present in master, I don't think it was because WP's behavior. I have another plugin that syncs passwords to a Drupal database that probably loaded the PasswordHash class so it didn't throw an error in password-hash plugin.

**Comment by My1** [comment]
oh. lol. well for testing whether a plugin works a vanilla installation is best.
